"""Mermaid.js diagram exporter.

Generates Mermaid diagram text (.mmd files) that render natively in:
- GitHub, GitLab, Bitbucket (fenced code blocks)
- Notion, Obsidian, Confluence (with plugins)
- VS Code (Mermaid Preview extension)
- Any browser (via Mermaid.js CDN)
- The built-in MUD Web UI at http://127.0.0.1:8042/
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from mudtool.models.json_uml import (
    ActivityDiagram,
    ActivityNodeType,
    AnyDiagram,
    ClassDiagram,
    ComponentDiagram,
    GenerationResult,
    SequenceDiagram,
    StateMachineDiagram,
)

logger = logging.getLogger(__name__)


class MermaidExporter:
    """Export JSON-UML diagrams to Mermaid.js text format."""

    def export_result(
        self,
        result: GenerationResult,
        output_dir: Path,
    ) -> list[Path]:
        """Export all diagrams in a generation result to .mmd files.

        Returns list of written file paths.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []

        for i, diagram in enumerate(result.diagrams):
            try:
                name = getattr(diagram, "name", "") or f"diagram_{i}"
                name = name.replace(" ", "_").replace("/", "_")
                suffix = diagram.diagram_type.value
                path = output_dir / f"{suffix}_{name}.mmd"

                content = self.export_diagram(diagram)
                path.write_text(content, encoding="utf-8")
                paths.append(path)

            except Exception as e:
                logger.error(f"Failed to export diagram {i} to Mermaid: {e}")

        return paths

    def export_result_inline(self, result: GenerationResult, *, preview: bool = False) -> dict[str, str]:
        """Export all diagrams as inline Mermaid text (for Web UI).

        Returns dict mapping diagram key → mermaid text string.
        Sub-diagrams (private function flowcharts) are flattened out
        with keys like `activity_RE_Control__fn__CalcTorque`.
        """
        diagrams: dict[str, str] = {}

        for i, diagram in enumerate(result.diagrams):
            try:
                name = getattr(diagram, "name", "") or f"diagram_{i}"
                suffix = diagram.diagram_type.value
                key = f"{suffix}_{name}"
                diagrams[key] = self.export_diagram(diagram, preview=preview)

                # Flatten sub-diagrams for hierarchical activity diagrams
                if isinstance(diagram, ActivityDiagram) and diagram.sub_diagrams:
                    for sub in diagram.sub_diagrams:
                        if preview and not self._include_subdiagram_in_preview(sub):
                            continue
                        sub_name = sub.function_name or sub.name or "sub"
                        sub_key = f"{suffix}_{name}__fn__{sub_name}"
                        diagrams[sub_key] = self.export_diagram(sub, preview=preview)

            except Exception as e:
                logger.error(f"Failed to export diagram {i} inline: {e}")

        return diagrams

    def export_diagram(self, diagram: AnyDiagram, *, preview: bool = False) -> str:
        """Export a single diagram to Mermaid text."""
        if isinstance(diagram, SequenceDiagram):
            return self._sequence_to_mermaid(diagram)
        elif isinstance(diagram, StateMachineDiagram):
            return self._state_machine_to_mermaid(diagram)
        elif isinstance(diagram, ClassDiagram):
            return self._class_to_mermaid(diagram)
        elif isinstance(diagram, ComponentDiagram):
            return self._component_to_mermaid(diagram)
        elif isinstance(diagram, ActivityDiagram):
            return self._activity_to_mermaid(diagram, preview=preview)
        return f"%% Unknown diagram type: {diagram.diagram_type}"

    def _include_subdiagram_in_preview(self, diagram: ActivityDiagram) -> bool:
        non_terminal = [
            n for n in diagram.nodes
            if n.node_type not in {ActivityNodeType.INITIAL, ActivityNodeType.FINAL}
        ]
        if len(non_terminal) < 2:
            return False
        meaningful = {
            ActivityNodeType.DECISION,
            ActivityNodeType.MERGE,
            ActivityNodeType.EXCEPTION,
            ActivityNodeType.CALL,
            ActivityNodeType.FUNCTION_CALL,
        }
        if any(n.node_type in meaningful for n in non_terminal):
            return True
        return len(non_terminal) >= 3

    def _sequence_to_mermaid(self, diagram: SequenceDiagram) -> str:
        lines = ["sequenceDiagram"]

        if diagram.name:
            lines.append(f"    title {diagram.name}")

        if diagram.provenance:
            lines.append(
                f"    %% Generated by {diagram.provenance.ai_model} "
                f"(confidence: {diagram.provenance.confidence})"
            )
        if diagram.source_requirements:
            lines.append(f"    %% Requirements: {', '.join(diagram.source_requirements)}")

        lines.append("")

        # Participants (lifelines)
        for ll in diagram.lifelines:
            stereotype = f"<br/>{ll.type}" if ll.type else ""
            lines.append(f"    participant {ll.id} as {ll.name}{stereotype}")

        lines.append("")

        # Messages
        for msg in diagram.messages:
            if msg.is_return:
                arrow = "-->>"
            elif msg.is_async:
                arrow = "->>"
            else:
                arrow = "->>"

            label = msg.label or ""
            if not label and msg.rte_call:
                parts = [msg.rte_call]
                if msg.port:
                    parts.append(msg.port)
                if msg.element:
                    parts.append(msg.element)
                label = f"{parts[0]}({', '.join(parts[1:])})"

            if msg.trace_req:
                label += f" [{msg.trace_req}]"

            lines.append(f"    {msg.from_lifeline}{arrow}{msg.to_lifeline}: {label}")

        return "\n".join(lines)

    def _state_machine_to_mermaid(self, diagram: StateMachineDiagram) -> str:
        lines = ["stateDiagram-v2"]

        if diagram.name:
            safe_diag_name = diagram.name.replace(chr(10), ' ').replace(chr(13), '')
            # "title" keyword is NOT valid in stateDiagram-v2 — use a comment
            lines.append(f"    %% {safe_diag_name}")
        if diagram.owner_swc:
            safe_swc = diagram.owner_swc.replace(chr(10), ' ').replace(chr(13), '')
            lines.append(f"    %% Owner SWC: {safe_swc}")

        lines.append("")

        import re
        def _safe_state(sid: str, name: str) -> str:
            s_name = name or sid
            # Scrape out LLM-hallucinated mermaid aliases (e.g. state "..." as ID)
            if '" as ' in s_name:
                s_name = s_name.split('" as ')[0].replace('"', '')
            if "' as " in s_name:
                s_name = s_name.split("' as ")[0].replace("'", "")
            return re.sub(r'[^a-zA-Z0-9_]', '_', s_name).strip('_')

        # Provide a mapping array for transitions
        state_map = {}
        for state in diagram.states:
            state_map[state.id] = _safe_state(state.id, state.name)

        # States
        for state in diagram.states:
            if state.is_initial or state.is_final:
                continue  # [*] is implicit in Mermaid

            safe_name = state_map[state.id]
            inline_actions = [a for a in state.actions
                              if a.action_type in ("entry", "exit")]
            note_actions   = [a for a in state.actions
                              if a.action_type not in ("entry", "exit")]

            if inline_actions:
                lines.append(f"    state {safe_name} {{")
                for action in inline_actions:
                    safe_desc = action.description.replace(chr(10), ' ').replace(chr(13), '')
                    lines.append(f"        {action.action_type}: {safe_desc}")
                lines.append("    }")
            else:
                lines.append(f"    state {safe_name}")

            note_lines = [
                f"{a.action_type}: {a.description.replace(chr(10), ' ').replace(chr(13), '')}"
                for a in note_actions
            ]
            if state.trace_reqs:
                note_lines.append(f"traces: {', '.join(state.trace_reqs)}")
            for nl in note_lines:
                lines.append(f"    %% {nl}")

        lines.append("")

        # Transitions
        for trans in diagram.transitions:
            source = trans.source
            target = trans.target

            source_state = next((s for s in diagram.states if s.id == source), None)
            target_state = next((s for s in diagram.states if s.id == target), None)

            source_name = state_map.get(source, _safe_state(source, source))
            target_name = state_map.get(target, _safe_state(target, target))

            if source_state and source_state.is_initial:
                source_name = "[*]"
            if target_state and target_state.is_final:
                target_name = "[*]"

            label_parts = []
            if trans.trigger:
                label_parts.append(trans.trigger)
            if trans.guard:
                label_parts.append(f"[{trans.guard.condition}]")
            if trans.action:
                label_parts.append(f"/ {trans.action}")

            label = " ".join(label_parts)
            safe_label = label.replace(chr(10), ' ').replace(chr(13), '')
            
            if safe_label:
                lines.append(f"    {source_name} --> {target_name} : {safe_label}")
            else:
                lines.append(f"    {source_name} --> {target_name}")

        return "\n".join(lines)

    def _class_to_mermaid(self, diagram: ClassDiagram) -> str:
        lines = ["classDiagram"]

        if diagram.name:
            lines.append(f"    %% {diagram.name}")
        if diagram.source_requirements:
            lines.append(f"    %% Requirements: {', '.join(diagram.source_requirements)}")

        lines.append("")

        for cls in diagram.classes:
            lines.append(f"    class {cls.name} {{")

            if cls.stereotype:
                lines.append(f"        <<{cls.stereotype}>>")

            for attr in cls.attributes:
                vis = {
                    "public": "+", "private": "-",
                    "protected": "#", "package": "~"
                }.get(attr.visibility.value, "+")
                lines.append(f"        {vis}{attr.name} {attr.data_type}")

            for op in cls.operations:
                vis = {
                    "public": "+", "private": "-",
                    "protected": "#", "package": "~"
                }.get(op.visibility.value, "+")
                ret = f" {op.return_type}" if op.return_type else ""
                trigger = f" [{op.trigger_type}]" if op.trigger_type else ""
                lines.append(f"        {vis}{op.name}(){ret}{trigger}")

            lines.append("    }")
            lines.append("")

        # Associations
        for assoc in diagram.associations:
            source_cls = next((c for c in diagram.classes if c.id == assoc.source), None)
            target_cls = next((c for c in diagram.classes if c.id == assoc.target), None)

            source_name = source_cls.name if source_cls else assoc.source
            target_name = target_cls.name if target_cls else assoc.target

            arrow = {
                "association": "-->",
                "aggregation": "o--",
                "composition": "*--",
                "dependency": "..>",
                "realization": "..|>",
            }.get(assoc.association_type.value, "-->")

            label = f" : {assoc.label}" if assoc.label else ""
            lines.append(f"    {source_name} {arrow} {target_name}{label}")

        return "\n".join(lines)

    def _component_to_mermaid(self, diagram: ComponentDiagram) -> str:
        lines = ["graph TD"]

        if diagram.name:
            lines.append(f"    %% {diagram.name}")
        if diagram.source_requirements:
            lines.append(f"    %% Requirements: {', '.join(diagram.source_requirements)}")

        lines.append("")

        # Components as nodes with port details
        for comp in diagram.components:
            comp_id = comp.id.replace("-", "_")
            stereotype = f"\\n«{comp.stereotype}»" if comp.stereotype else ""

            port_names = [p.name for p in comp.ports[:4]]  # Show up to 4 ports
            port_text = ""
            if port_names:
                port_text = "\\n" + " | ".join(port_names)

            lines.append(f'    {comp_id}["{comp.name}{stereotype}{port_text}"]')

        lines.append("")

        # Connectors as edges
        seen_edges: set[str] = set()
        for conn in diagram.connectors:
            src = conn.source_component.replace("-", "_")
            tgt = conn.target_component.replace("-", "_")
            edge_key = f"{src}--{tgt}"
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)

            label = f"|{conn.label}|" if conn.label else ""
            lines.append(f"    {src} -->{label} {tgt}")

        return "\n".join(lines)

    def _activity_to_mermaid(self, diagram: ActivityDiagram, *, preview: bool = False) -> str:
        lines = ["flowchart TD"]

        if not preview and (diagram.owner_swc or diagram.owner_runnable):
            swc_part = f"SWC: {diagram.owner_swc}" if diagram.owner_swc else ""
            run_part = f"Runnable: {diagram.owner_runnable}" if diagram.owner_runnable else ""
            comment = " / ".join(filter(None, [swc_part, run_part]))
            lines.append(f"    %% {comment}")

        if not preview and diagram.name:
            lines.append(f"    %% {diagram.name}")

        if not preview and diagram.provenance:
            lines.append(
                f"    %% Generated by {diagram.provenance.ai_model} "
                f"(confidence: {diagram.provenance.confidence})"
            )
        if not preview and diagram.source_requirements:
            lines.append(f"    %% Requirements: {', '.join(diagram.source_requirements)}")

        lines.append("")

        def _safe(nid: str) -> str:
            """Convert node id to a safe Mermaid identifier."""
            safe = re.sub(r"[^A-Za-z0-9_]+", "_", nid or "")
            safe = re.sub(r"_+", "_", safe).strip("_")
            if not safe or not re.match(r"[A-Za-z_]", safe):
                safe = f"N_{abs(hash(nid or 'node')) % 100000}"
            return safe

        def _q(text: str) -> str:
            """Quote a label for safe use inside Mermaid node shapes.

            Rules:
            - Wrap in double quotes so (, ), :, >, <, = etc. are treated as literal text
            - Replace literal backslash-n with <br/> for line breaks
            - Escape embedded double-quotes as #quot;
            - Replace C logical operators (||, &&) to avoid Mermaid pipe-char conflicts
            """
            safe = (
                text
                .replace('"', "#quot;")
                .replace("\\n", "<br/>")
                .replace("||", " OR ")    # C logical-or breaks flowchart parser
                .replace("|", " PIPE ")   # lone pipe → word form (Mermaid is not an HTML parser)
                .replace("&&", " AND ")   # C logical-and (sanitize for safety)
            )
            # Auto-wrap long pseudocode labels at ~60 chars for readability
            if len(safe) > 60 and "<br/>" not in safe:
                mid = len(safe) // 2
                for i in range(mid, min(mid + 15, len(safe))):
                    if safe[i] in (',', ' '):
                        safe = safe[:i + 1] + "<br/>" + safe[i + 1:]
                        break
            return f'"{safe}"'

        def _preview_label(text: str) -> str:
            if not preview:
                return text
            safe = re.sub(r"\s+", " ", text or "").strip()
            if len(safe) <= 48:
                return safe
            if "(" in safe and ")" in safe:
                fn_match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*\(", safe)
                if fn_match:
                    return f"{fn_match.group(1)}(...)"
            assign = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$", safe)
            if assign:
                rhs = assign.group(2).strip()
                fn_match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*\(", rhs)
                if fn_match:
                    fn_name = fn_match.group(1)
                    if len(fn_name) > 24:
                        return f"{assign.group(1)} = call(...)"
                    return f"{assign.group(1)} = {fn_name}(...)"
                return f"{assign.group(1)} = ..."
            return safe[:45].rstrip() + "..."

        def _guard(g: str) -> str:
            """Sanitize a guard string for use in Mermaid -->|guard| edge labels.

            The pipe character | terminates the guard prematurely, so C logical-or
            (||) must be replaced with a word form.  Parentheses and angle brackets
            also confuse the Mermaid edge-label parser, so replace them with
            readable equivalents.
            """
            g = g.strip()
            if g.startswith("[") and g.endswith("]"):
                g = g[1:-1]
            # Replace chars that break Mermaid edge-label parsing
            g = g.replace("||", " OR ").replace("|", " OR ").replace("&&", " AND ")
            g = g.replace("(", "&#40;").replace(")", "&#41;")
            g = g.replace(">", "&gt;").replace("<", "&lt;")
            g = g.replace('"', "'")
            return g.strip()

        # Emit nodes — traces go on a %% comment line BEFORE the node (never inline)
        for node in diagram.nodes:
            nid = _safe(node.id)

            # Trace comment on its own line (valid Mermaid; inline %% after node breaks parser)
            if node.trace_reqs and not preview:
                lines.append(f"    %% traces: {', '.join(node.trace_reqs)}")

            if node.node_type == ActivityNodeType.INITIAL:
                lines.append(f"    {nid}([{_q('Start')}])")

            elif node.node_type == ActivityNodeType.FINAL:
                lines.append(f"    {nid}([{_q('End')}])")

            elif node.node_type == ActivityNodeType.DECISION:
                # Put full C description as %% comment above the diamond.
                # Never embed C expressions directly in the label — || breaks the parser.
                # Strip newlines — a multi-line %% comment breaks Mermaid's parser.
                if node.description and not preview:
                    safe_desc = node.description.replace('\r', '').replace('\n', ' ')
                    lines.append(f"    %% decision: {safe_desc}")
                lines.append(f"    {nid}{{{_q(_preview_label(node.name))}}}")

            elif node.node_type == ActivityNodeType.CALL:
                # Prefer node.name if it already contains a C-style call
                if "(" in node.name and ")" in node.name:
                    call_label = node.name
                else:
                    # Legacy fallback: construct from rte_call/port/element
                    parts = [p for p in [node.rte_call, node.port, node.element] if p]
                    if len(parts) > 1:
                        call_label = f"RTE: {parts[0]}({', '.join(parts[1:])})"
                    elif parts:
                        call_label = f"RTE: {parts[0]}"
                    else:
                        call_label = f"RTE: {node.name}"
                lines.append(f"    {nid}[{_q(_preview_label(call_label))}]")

            elif node.node_type == ActivityNodeType.FUNCTION_CALL:
                # Private function call: subroutine box [[label]]
                callee_name = node.callee or node.name
                func_label = f"{callee_name}()"
                if node.description:
                    func_label = node.description
                if not preview:
                    lines.append(f"    %% → see sub-diagram: {callee_name}")
                lines.append(f"    {nid}[[{_q(_preview_label(func_label))}]]")
                # Mermaid click callback — navigates to the sub-diagram card in the Web UI.
                # Requires securityLevel:'loose' (already set in the Web UI's mermaid.initialize).
                lines.append(f'    click {nid} navigateToSubDiagram "{callee_name}"')

            elif node.node_type == ActivityNodeType.EXCEPTION:
                # Keep short: just the node name (description may contain parens that confuse parser)
                lines.append(f"    {nid}[/{_q(_preview_label('FAULT: ' + node.name))}/]")

            elif node.node_type in (ActivityNodeType.FORK, ActivityNodeType.JOIN):
                lines.append(f"    {nid}({_q(_preview_label(node.name))})")

            elif node.node_type == ActivityNodeType.MERGE:
                lines.append(f"    {nid}({_q(node.name)})")

            else:  # ACTION
                label = _preview_label(node.name)
                lines.append(f"    {nid}[{_q(label)}]")

        lines.append("")

        # Emit edges
        for edge in diagram.edges:
            src = _safe(edge.source)
            tgt = _safe(edge.target)
            raw_guard = edge.guard or edge.label
            if raw_guard:
                # Sanitize guard: strip [], replace C pipe-operators with words
                g = _guard(raw_guard)
                lines.append(f"    {src} -->|{g}| {tgt}")
            else:
                lines.append(f"    {src} --> {tgt}")

        # ── Node styling: color-code by type ──────────────────────────
        lines.append("")
        lines.append("    %% Node type styling")
        lines.append("    classDef rteCall fill:#d4e6f1,stroke:#2980b9,color:#000")
        lines.append("    classDef decision fill:#fdebd0,stroke:#e67e22,color:#000")
        lines.append("    classDef exception fill:#f5b7b1,stroke:#e74c3c,color:#000")
        lines.append("    classDef funcCall fill:#d5f5e3,stroke:#27ae60,color:#000")
        lines.append("    classDef initial fill:#d5dbdb,stroke:#566573,color:#000")
        lines.append("    classDef final fill:#566573,stroke:#2c3e50,color:#fff")
        lines.append("    classDef action fill:#ebf5fb,stroke:#3498db,color:#000")

        # Assign classes to nodes
        type_to_class = {
            ActivityNodeType.CALL: "rteCall",
            ActivityNodeType.DECISION: "decision",
            ActivityNodeType.EXCEPTION: "exception",
            ActivityNodeType.FUNCTION_CALL: "funcCall",
            ActivityNodeType.INITIAL: "initial",
            ActivityNodeType.FINAL: "final",
            ActivityNodeType.ACTION: "action",
        }
        for node in diagram.nodes:
            css_class = type_to_class.get(node.node_type)
            if css_class:
                lines.append(f"    class {_safe(node.id)} {css_class}")

        return "\n".join(lines)
