"""PlantUML text exporter for quick previews, diffs, and reviews.

Generates PlantUML text as a secondary view format. Useful for:
- Quick visual previews without Modelio
- Git-friendly text diffs
- Lightweight code review of model changes
"""

from __future__ import annotations

import logging
from pathlib import Path

from mudtool.models.json_uml import (
    ActivityDiagram,
    ActivityNodeType,
    AnyDiagram,
    ClassDiagram,
    ComponentDiagram,
    GenerationResult,
    SequenceDiagram,
    StateMachineDiagram,
)

logger = logging.getLogger(__name__)


class PlantUMLExporter:
    """Export JSON-UML diagrams to PlantUML text format."""

    def export_result(
        self,
        result: GenerationResult,
        output_dir: Path,
    ) -> list[Path]:
        """Export all diagrams in a generation result to PlantUML files.

        Returns list of written file paths.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []

        for i, diagram in enumerate(result.diagrams):
            try:
                name = getattr(diagram, "name", "") or f"diagram_{i}"
                name = name.replace(" ", "_").replace("/", "_")
                suffix = diagram.diagram_type.value
                path = output_dir / f"{suffix}_{name}.puml"

                content = self.export_diagram(diagram)
                path.write_text(content, encoding="utf-8")
                paths.append(path)

            except Exception as e:
                logger.error(f"Failed to export diagram {i} to PlantUML: {e}")

        return paths

    def export_diagram(self, diagram: AnyDiagram) -> str:
        """Export a single diagram to PlantUML text."""
        if isinstance(diagram, SequenceDiagram):
            return self._export_sequence(diagram)
        elif isinstance(diagram, StateMachineDiagram):
            return self._export_state_machine(diagram)
        elif isinstance(diagram, ClassDiagram):
            return self._export_class_diagram(diagram)
        elif isinstance(diagram, ComponentDiagram):
            return self._export_component_diagram(diagram)
        elif isinstance(diagram, ActivityDiagram):
            return self._export_activity(diagram)
        return f"' Unknown diagram type: {diagram.diagram_type}"

    def _export_sequence(self, diagram: SequenceDiagram) -> str:
        lines = ["@startuml"]
        lines.append(f"title {diagram.name or 'Sequence Diagram'}")
        lines.append("")

        # Header with provenance
        if diagram.provenance:
            lines.append(
                f"' Generated by {diagram.provenance.ai_model} "
                f"(confidence: {diagram.provenance.confidence})"
            )

        # Source requirements
        if diagram.source_requirements:
            lines.append(f"' Requirements: {', '.join(diagram.source_requirements)}")
        lines.append("")

        # Participants (lifelines)
        for ll in diagram.lifelines:
            stereotype = f" <<{ll.type}>>" if ll.type else ""
            lines.append(f'participant "{ll.name}"{stereotype} as {ll.id}')

        lines.append("")

        # Messages
        for msg in diagram.messages:
            arrow = "-->" if msg.is_async else "->"
            if msg.is_return:
                arrow = "-->"

            label = msg.label or ""
            if not label and msg.rte_call:
                parts = [msg.rte_call]
                if msg.port:
                    parts.append(msg.port)
                if msg.element:
                    parts.append(msg.element)
                label = f"{parts[0]}({', '.join(parts[1:])})"

            if msg.trace_req:
                label += f" [{msg.trace_req}]"

            lines.append(f"{msg.from_lifeline} {arrow} {msg.to_lifeline}: {label}")

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)

    def _export_state_machine(self, diagram: StateMachineDiagram) -> str:
        lines = ["@startuml"]
        lines.append(f"title {diagram.name or 'State Machine'}")

        if diagram.owner_swc:
            lines.append(f"' Owner SWC: {diagram.owner_swc}")
        lines.append("")

        # States
        for state in diagram.states:
            if state.is_initial:
                lines.append(f"[*] --> {state.name}")
                continue
            if state.is_final:
                continue  # Final states handled via transitions

            state_body = []
            for action in state.actions:
                state_body.append(f"{action.action_type} / {action.description}")

            if state_body:
                lines.append(f"state {state.name} {{")
                for body_line in state_body:
                    lines.append(f"  {body_line}")
                lines.append("}")
            else:
                lines.append(f"state {state.name}")

        lines.append("")

        # Transitions
        for trans in diagram.transitions:
            source = trans.source
            target = trans.target

            # Resolve state names from IDs
            source_state = next(
                (s for s in diagram.states if s.id == source), None
            )
            target_state = next(
                (s for s in diagram.states if s.id == target), None
            )

            source_name = source_state.name if source_state else source
            target_name = target_state.name if target_state else target

            if source_state and source_state.is_initial:
                source_name = "[*]"
            if target_state and target_state.is_final:
                target_name = "[*]"

            label_parts = []
            if trans.trigger:
                label_parts.append(trans.trigger)
            if trans.guard:
                label_parts.append(f"[{trans.guard.condition}]")
            if trans.action:
                label_parts.append(f"/ {trans.action}")

            label = " ".join(label_parts)
            if label:
                lines.append(f"{source_name} --> {target_name} : {label}")
            else:
                lines.append(f"{source_name} --> {target_name}")

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)

    def _export_class_diagram(self, diagram: ClassDiagram) -> str:
        lines = ["@startuml"]
        lines.append(f"title {diagram.name or 'Class Diagram'}")
        lines.append("")

        for cls in diagram.classes:
            stereotype = f" <<{cls.stereotype}>>" if cls.stereotype else ""
            lines.append(f"class {cls.name}{stereotype} {{")

            for attr in cls.attributes:
                vis = {"public": "+", "private": "-", "protected": "#", "package": "~"}.get(
                    attr.visibility.value, "+"
                )
                lines.append(f"  {vis} {attr.name}: {attr.data_type}")

            if cls.attributes and cls.operations:
                lines.append("  --")

            for op in cls.operations:
                vis = {"public": "+", "private": "-", "protected": "#", "package": "~"}.get(
                    op.visibility.value, "+"
                )
                trigger = f" <<{op.trigger_type}>>" if op.trigger_type else ""
                ret = f": {op.return_type}" if op.return_type else ""
                lines.append(f"  {vis} {op.name}(){ret}{trigger}")

            lines.append("}")
            lines.append("")

        # Associations
        for assoc in diagram.associations:
            # Use class names if available
            source_cls = next(
                (c for c in diagram.classes if c.id == assoc.source), None
            )
            target_cls = next(
                (c for c in diagram.classes if c.id == assoc.target), None
            )

            source_name = source_cls.name if source_cls else assoc.source
            target_name = target_cls.name if target_cls else assoc.target

            arrow = {
                "association": "-->",
                "aggregation": "o--",
                "composition": "*--",
                "dependency": "..>",
                "realization": "..|>",
            }.get(assoc.association_type.value, "-->")

            label = f" : {assoc.label}" if assoc.label else ""
            lines.append(f"{source_name} {arrow} {target_name}{label}")

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)

    def _export_component_diagram(self, diagram: ComponentDiagram) -> str:
        lines = ["@startuml"]
        lines.append(f"title {diagram.name or 'Component Diagram'}")
        lines.append("")

        for comp in diagram.components:
            lines.append(f"component [{comp.name}] as {comp.id} {{")

            for port in comp.ports:
                direction = "<<P-Port>>" if port.direction == "provided" else "<<R-Port>>"
                lines.append(f"  portin \"{port.name}\" as {port.id} {direction}")

            lines.append("}")
            lines.append("")

        # Connectors
        for conn in diagram.connectors:
            label = f" : {conn.label}" if conn.label else ""
            lines.append(
                f"{conn.source_component} --> {conn.target_component}{label}"
            )

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)

    def _export_activity(self, diagram: ActivityDiagram) -> str:
        """Export an activity / code-flow diagram to PlantUML."""
        lines = ["@startuml"]
        lines.append(f"title {diagram.name or 'Activity Diagram'}")

        if diagram.owner_swc:
            lines.append(f"' Owner SWC: {diagram.owner_swc}")
        if diagram.owner_runnable:
            lines.append(f"' Runnable: {diagram.owner_runnable}")
        if diagram.provenance:
            lines.append(
                f"' Generated by {diagram.provenance.ai_model} "
                f"(confidence: {diagram.provenance.confidence})"
            )
        if diagram.source_requirements:
            lines.append(f"' Requirements: {', '.join(diagram.source_requirements)}")
        lines.append("")

        # Build adjacency list for edge traversal
        node_map = {n.id: n for n in diagram.nodes}
        outgoing: dict[str, list] = {}
        for edge in diagram.edges:
            outgoing.setdefault(edge.source, []).append(edge)

        # Track visited nodes to avoid infinite loops
        visited: set[str] = set()

        def _emit_node(node_id: str) -> None:
            if node_id in visited:
                return
            visited.add(node_id)

            node = node_map.get(node_id)
            if not node:
                return

            edges = outgoing.get(node_id, [])

            if node.node_type == ActivityNodeType.INITIAL:
                lines.append("start")
                for e in edges:
                    _emit_node(e.target)

            elif node.node_type == ActivityNodeType.FINAL:
                lines.append("stop")

            elif node.node_type == ActivityNodeType.DECISION:
                label = node.name.replace('"', "'")
                if edges:
                    true_edge = edges[0]
                    guard_true = (true_edge.guard or true_edge.label or "yes").strip("[]")
                    lines.append(f'if ({label}) then ({guard_true})')
                    _emit_node(true_edge.target)

                    for alt_edge in edges[1:]:
                        guard_alt = (alt_edge.guard or alt_edge.label or "no").strip("[]")
                        if len(edges) == 2:
                            lines.append(f"else ({guard_alt})")
                        else:
                            lines.append(f"elseif ({guard_alt}) then")
                        _emit_node(alt_edge.target)

                    lines.append("endif")

            elif node.node_type == ActivityNodeType.MERGE:
                # Merges are implicit in PlantUML activity diagrams
                for e in edges:
                    _emit_node(e.target)

            elif node.node_type == ActivityNodeType.FORK:
                lines.append("fork")
                for i, e in enumerate(edges):
                    if i > 0:
                        lines.append("fork again")
                    _emit_node(e.target)
                lines.append("end fork")

            elif node.node_type == ActivityNodeType.JOIN:
                # Joins paired with fork — continue to next
                for e in edges:
                    _emit_node(e.target)

            elif node.node_type == ActivityNodeType.EXCEPTION:
                desc = node.description or node.name
                desc = desc.replace('"', "'")
                lines.append(f"#pink:{desc};")
                for e in edges:
                    _emit_node(e.target)

            elif node.node_type == ActivityNodeType.CALL:
                desc = node.description or node.name
                desc = desc.replace('"', "'")
                lines.append(f":{desc};")
                for e in edges:
                    _emit_node(e.target)

            elif node.node_type == ActivityNodeType.FUNCTION_CALL:
                callee_name = node.callee or node.name
                desc = node.description or f"call {callee_name}()"
                desc = desc.replace('"', "'")
                lines.append(f"partition \"{callee_name}()\" {{")
                lines.append(f"  :{desc};")
                lines.append("}")
                for e in edges:
                    _emit_node(e.target)

            else:  # ACTION
                desc = node.description or node.name
                desc = desc.replace('"', "'")
                lines.append(f":{desc};")
                for e in edges:
                    _emit_node(e.target)

        # Find the initial node and start traversal
        initial_nodes = [
            n for n in diagram.nodes
            if n.node_type == ActivityNodeType.INITIAL
        ]
        if initial_nodes:
            _emit_node(initial_nodes[0].id)
        else:
            # Fallback: emit nodes linearly
            for node in diagram.nodes:
                if node.node_type == ActivityNodeType.INITIAL:
                    lines.append("start")
                elif node.node_type == ActivityNodeType.FINAL:
                    lines.append("stop")
                else:
                    label = node.description or node.name
                    label = label.replace('"', "'")
                    lines.append(f":{label};")

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)
