"""XMI (UML 2.x) Exporter - converts JSON-UML models to XMI format.

XMI is the canonical model storage format, enabling interoperability
with Papyrus, Enterprise Architect, Rhapsody, and Modelio.
"""

from __future__ import annotations

import logging
import uuid
from pathlib import Path
from typing import Optional
from xml.etree.ElementTree import Element, SubElement, ElementTree, tostring, indent

from mudtool.models.json_uml import (
    AnyDiagram,
    ClassDiagram,
    ClassElement,
    ComponentDiagram,
    GenerationResult,
    SequenceDiagram,
    StateMachineDiagram,
)

logger = logging.getLogger(__name__)

# XMI and UML namespace URIs
XMI_NS = "http://www.omg.org/spec/XMI/20131001"
UML_NS = "http://www.omg.org/spec/UML/20131001"
AUTOSAR_NS = "http://autosar.org/schema/r4.0"


def _uid() -> str:
    """Generate a unique XMI ID."""
    return f"_mud_{uuid.uuid4().hex[:12]}"


class XMIExporter:
    """Export JSON-UML diagrams to XMI (UML 2.x) format."""

    def __init__(self):
        self._id_map: dict[str, str] = {}  # JSON-UML id -> XMI id

    def export_result(
        self,
        result: GenerationResult,
        output_path: Path,
        model_name: str = "MUD_Generated_Model",
    ) -> Path:
        """Export a complete generation result to XMI.

        Args:
            result: The generation result containing diagrams.
            output_path: Path to write the XMI file.
            model_name: Name for the root UML model.

        Returns:
            Path to the written XMI file.
        """
        self._id_map = {}

        root = Element("xmi:XMI")
        root.set("xmlns:xmi", XMI_NS)
        root.set("xmlns:uml", UML_NS)
        root.set("xmi:version", "2.5.1")

        # Create root model
        model = SubElement(root, "uml:Model")
        model.set("xmi:type", "uml:Model")
        model.set("xmi:id", _uid())
        model.set("name", model_name)

        for diagram in result.diagrams:
            try:
                self._export_diagram(model, diagram)
            except Exception as e:
                logger.error(f"Failed to export diagram to XMI: {e}")

        # Write file
        indent(root, space="  ")
        tree = ElementTree(root)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        tree.write(str(output_path), encoding="unicode", xml_declaration=True)

        logger.info(f"XMI exported to {output_path}")
        return output_path

    def _export_diagram(self, parent: Element, diagram: AnyDiagram) -> None:
        """Export a single diagram to XMI elements under the parent."""
        if isinstance(diagram, SequenceDiagram):
            self._export_sequence(parent, diagram)
        elif isinstance(diagram, StateMachineDiagram):
            self._export_state_machine(parent, diagram)
        elif isinstance(diagram, ClassDiagram):
            self._export_class_diagram(parent, diagram)
        elif isinstance(diagram, ComponentDiagram):
            self._export_component_diagram(parent, diagram)

    def _export_sequence(self, parent: Element, diagram: SequenceDiagram) -> None:
        """Export sequence diagram as UML Interaction."""
        # Package for sequence diagrams
        pkg = SubElement(parent, "packagedElement")
        pkg.set("xmi:type", "uml:Package")
        pkg.set("xmi:id", _uid())
        pkg.set("name", f"Sequences_{diagram.name or 'Generated'}")

        interaction = SubElement(pkg, "packagedElement")
        interaction.set("xmi:type", "uml:Interaction")
        interaction_id = _uid()
        interaction.set("xmi:id", interaction_id)
        interaction.set("name", diagram.name or "GeneratedSequence")

        # Add provenance as comment
        if diagram.provenance:
            self._add_comment(
                interaction,
                f"Generated by {diagram.provenance.ai_model} "
                f"(confidence: {diagram.provenance.confidence})",
            )

        # Add source requirement traceability
        for req_id in diagram.source_requirements:
            self._add_tagged_value(interaction, "trace_req", req_id)

        # Lifelines
        lifeline_xmi_ids: dict[str, str] = {}
        for ll in diagram.lifelines:
            ll_elem = SubElement(interaction, "lifeline")
            ll_xmi_id = _uid()
            ll_elem.set("xmi:type", "uml:Lifeline")
            ll_elem.set("xmi:id", ll_xmi_id)
            ll_elem.set("name", ll.name)
            lifeline_xmi_ids[ll.id] = ll_xmi_id

            # AUTOSAR stereotype
            if ll.type:
                self._add_tagged_value(ll_elem, "autosar_type", ll.type)
            if ll.runnable:
                self._add_tagged_value(ll_elem, "runnable", ll.runnable)

        # Messages
        for msg in diagram.messages:
            msg_elem = SubElement(interaction, "message")
            msg_elem.set("xmi:type", "uml:Message")
            msg_elem.set("xmi:id", _uid())
            msg_elem.set("name", msg.label or "")

            from_id = lifeline_xmi_ids.get(msg.from_lifeline, "")
            to_id = lifeline_xmi_ids.get(msg.to_lifeline, "")
            msg_elem.set("sendEvent", from_id)
            msg_elem.set("receiveEvent", to_id)

            if msg.is_return:
                msg_elem.set("messageSort", "reply")
            elif msg.is_async:
                msg_elem.set("messageSort", "asynchCall")
            else:
                msg_elem.set("messageSort", "synchCall")

            # AUTOSAR RTE call info
            if msg.rte_call:
                self._add_tagged_value(msg_elem, "rte_call", msg.rte_call)
            if msg.port:
                self._add_tagged_value(msg_elem, "port", msg.port)
            if msg.element:
                self._add_tagged_value(msg_elem, "element", msg.element)
            if msg.trace_req:
                self._add_tagged_value(msg_elem, "trace_req", msg.trace_req)

    def _export_state_machine(
        self, parent: Element, diagram: StateMachineDiagram
    ) -> None:
        """Export state machine diagram as UML StateMachine."""
        sm = SubElement(parent, "packagedElement")
        sm.set("xmi:type", "uml:StateMachine")
        sm.set("xmi:id", _uid())
        sm.set("name", diagram.name or "GeneratedStateMachine")

        if diagram.owner_swc:
            self._add_tagged_value(sm, "owner_swc", diagram.owner_swc)

        # Region (required container for states)
        region = SubElement(sm, "region")
        region.set("xmi:type", "uml:Region")
        region.set("xmi:id", _uid())
        region.set("name", "MainRegion")

        state_xmi_ids: dict[str, str] = {}

        for state in diagram.states:
            state_elem = SubElement(region, "subvertex")
            state_xmi_id = _uid()
            state_elem.set("xmi:id", state_xmi_id)
            state_xmi_ids[state.id] = state_xmi_id

            if state.is_initial:
                state_elem.set("xmi:type", "uml:Pseudostate")
                state_elem.set("kind", "initial")
            elif state.is_final:
                state_elem.set("xmi:type", "uml:FinalState")
            else:
                state_elem.set("xmi:type", "uml:State")

            state_elem.set("name", state.name)

            # State actions
            for action in state.actions:
                if action.action_type == "entry":
                    entry = SubElement(state_elem, "entry")
                    entry.set("xmi:type", "uml:Activity")
                    entry.set("xmi:id", _uid())
                    entry.set("name", action.description)
                elif action.action_type == "exit":
                    exit_elem = SubElement(state_elem, "exit")
                    exit_elem.set("xmi:type", "uml:Activity")
                    exit_elem.set("xmi:id", _uid())
                    exit_elem.set("name", action.description)

            for req_id in state.trace_reqs:
                self._add_tagged_value(state_elem, "trace_req", req_id)

        # Transitions
        for trans in diagram.transitions:
            t_elem = SubElement(region, "transition")
            t_elem.set("xmi:type", "uml:Transition")
            t_elem.set("xmi:id", _uid())
            t_elem.set("source", state_xmi_ids.get(trans.source, ""))
            t_elem.set("target", state_xmi_ids.get(trans.target, ""))

            if trans.trigger:
                trigger = SubElement(t_elem, "trigger")
                trigger.set("xmi:type", "uml:Trigger")
                trigger.set("xmi:id", _uid())
                trigger.set("name", trans.trigger)

            if trans.guard:
                guard = SubElement(t_elem, "guard")
                guard.set("xmi:type", "uml:Constraint")
                guard.set("xmi:id", _uid())
                spec = SubElement(guard, "specification")
                spec.set("xmi:type", "uml:OpaqueExpression")
                spec.set("xmi:id", _uid())
                body = SubElement(spec, "body")
                body.text = trans.guard.condition

    def _export_class_diagram(self, parent: Element, diagram: ClassDiagram) -> None:
        """Export class diagram as UML Classes."""
        pkg = SubElement(parent, "packagedElement")
        pkg.set("xmi:type", "uml:Package")
        pkg.set("xmi:id", _uid())
        pkg.set("name", f"SWC_Design_{diagram.name or 'Generated'}")

        class_xmi_ids: dict[str, str] = {}

        for cls in diagram.classes:
            cls_elem = SubElement(pkg, "packagedElement")
            cls_elem.set("xmi:type", "uml:Class")
            cls_xmi_id = _uid()
            cls_elem.set("xmi:id", cls_xmi_id)
            cls_elem.set("name", cls.name)
            class_xmi_ids[cls.id] = cls_xmi_id

            if cls.stereotype:
                self._add_tagged_value(cls_elem, "stereotype", cls.stereotype)

            # Attributes
            for attr in cls.attributes:
                prop = SubElement(cls_elem, "ownedAttribute")
                prop.set("xmi:type", "uml:Property")
                prop.set("xmi:id", _uid())
                prop.set("name", attr.name)
                prop.set("visibility", attr.visibility.value)
                if attr.data_type:
                    self._add_tagged_value(prop, "type", attr.data_type)

            # Operations (Runnables)
            for op in cls.operations:
                op_elem = SubElement(cls_elem, "ownedOperation")
                op_elem.set("xmi:type", "uml:Operation")
                op_elem.set("xmi:id", _uid())
                op_elem.set("name", op.name)
                op_elem.set("visibility", op.visibility.value)

                if op.trigger_type:
                    self._add_tagged_value(op_elem, "trigger_type", op.trigger_type)
                if op.period_ms:
                    self._add_tagged_value(op_elem, "period_ms", str(op.period_ms))
                for req_id in op.trace_reqs:
                    self._add_tagged_value(op_elem, "trace_req", req_id)

            for req_id in cls.trace_reqs:
                self._add_tagged_value(cls_elem, "trace_req", req_id)

        # Associations
        for assoc in diagram.associations:
            a_elem = SubElement(pkg, "packagedElement")
            a_elem.set("xmi:type", "uml:Association")
            a_elem.set("xmi:id", _uid())
            if assoc.label:
                a_elem.set("name", assoc.label)

            # Member ends
            end1 = SubElement(a_elem, "memberEnd")
            end1.set("xmi:idref", class_xmi_ids.get(assoc.source, ""))
            end2 = SubElement(a_elem, "memberEnd")
            end2.set("xmi:idref", class_xmi_ids.get(assoc.target, ""))

    def _export_component_diagram(
        self, parent: Element, diagram: ComponentDiagram
    ) -> None:
        """Export component diagram as UML Components."""
        pkg = SubElement(parent, "packagedElement")
        pkg.set("xmi:type", "uml:Package")
        pkg.set("xmi:id", _uid())
        pkg.set("name", f"Architecture_{diagram.name or 'Generated'}")

        comp_xmi_ids: dict[str, str] = {}

        for comp in diagram.components:
            comp_elem = SubElement(pkg, "packagedElement")
            comp_elem.set("xmi:type", "uml:Component")
            comp_xmi_id = _uid()
            comp_elem.set("xmi:id", comp_xmi_id)
            comp_elem.set("name", comp.name)
            comp_xmi_ids[comp.id] = comp_xmi_id

            for port in comp.ports:
                port_elem = SubElement(comp_elem, "ownedPort")
                port_elem.set("xmi:type", "uml:Port")
                port_elem.set("xmi:id", _uid())
                port_elem.set("name", port.name)
                port_elem.set("isBehavior", "true")

                self._add_tagged_value(port_elem, "direction", port.direction)
                if port.interface_ref:
                    self._add_tagged_value(port_elem, "interface_ref", port.interface_ref)

        # Connectors
        for conn in diagram.connectors:
            c_elem = SubElement(pkg, "packagedElement")
            c_elem.set("xmi:type", "uml:Connector")
            c_elem.set("xmi:id", _uid())
            if conn.label:
                c_elem.set("name", conn.label)

            end1 = SubElement(c_elem, "end")
            end1.set("role", comp_xmi_ids.get(conn.source_component, ""))
            end2 = SubElement(c_elem, "end")
            end2.set("role", comp_xmi_ids.get(conn.target_component, ""))

    def _add_comment(self, parent: Element, text: str) -> None:
        """Add a UML comment to an element."""
        comment = SubElement(parent, "ownedComment")
        comment.set("xmi:type", "uml:Comment")
        comment.set("xmi:id", _uid())
        body = SubElement(comment, "body")
        body.text = text

    def _add_tagged_value(self, parent: Element, tag: str, value: str) -> None:
        """Add a tagged value (custom property) to an element."""
        tv = SubElement(parent, "ownedComment")
        tv.set("xmi:type", "uml:Comment")
        tv.set("xmi:id", _uid())
        body = SubElement(tv, "body")
        body.text = f"@{tag}={value}"
